apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-reviews
  namespace: argocd
  labels:
    app: reviews
    environment: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: prod-bookinfo
  source:
    kustomize:
    path: deploy/overlays/prod
    repoURL: https://github.com/makocchan0509/bookinfo-manifests.git
    targetRevision: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true
