apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: production
  app.kubernetes.io/managed-by: kustomize
namespace: prod

images:
- digest: sha256:42e7ac441e45bd8574f55d028134847af17951516d31574538944eb865754770
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: ghcr.io/makocchan0509/bookinfo/reviews

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- serviceaccount.yaml
