apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: production
  app.kubernetes.io/managed-by: kustomize
namespace: prod

images:
- newTag: 7fc8755e0b61a040e7cf89cc8eae0642de0686af
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: ghcr.io/makocchan0509/bookinfo/reviews

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- serviceaccount.yaml
