apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tekton-mac
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: /Users/makotomase/workspace/k8s-cicd
