apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: reviews-topic-listener
spec:
  serviceAccountName: tekton-admin
  triggers:
  - name: push-events-topic-branches
    interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
        params:
        - name: "secretRef"
          value:
            secretName: github-webhook-token
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
    template:
      ref: build-deploy-bookinfo-template
    bindings:
      - ref: build-deploy-reviews-binding
