apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kubectl-deploy-reviews-run-
spec:
  serviceAccountName: tekton-admin
  taskRef:
    name: kubectl-bookinfo
  workspaces:
    - name: manifest-dir
      persistentVolumeClaim:
        claimName: bookinfo-manifests
  params:
    - name: TARGET_APP
      value: reviews
    - name: IMAGE
      value: ghcr.io/makocchan0509/bookinfo/reviews
    - name: IMAGE_DIGEST
      value: sha256:c8671b1c47191d2d1f9d8774a469176c882f472ebc8b5f646c1e29a3d716ec3f
