apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: build-deploy-reviews-binding
spec:
  params:
  - name: TARGET-APP
    value: reviews
  - name: GITLAB-PROJECT-PATH
    value: $(body.repository.full_name)
  - name: BOOKINFO-URL
    value: $(body.repository.url)
  - name: BOOKINFO-REVISION
    value: $(body.head_commit.id)
