apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ci-reviews-binding
spec:
  params:
  - name: TARGET-APP
    value: reviews
  - name: GITLAB-PROJECT-PATH
    value: $(body.repository.full_name)
  - name: BOOKINFO-URL
    value: $(body.repository.clone_url)
  - name: BOOKINFO-REVISION
    value: $(body.pull_request.head.sha)
  - name: BOOKINFO-USERNAME
    value: $(body.pull_request.user.login)

