apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    tekton.dev/git-0: https://github.com
    tekton.dev/docker-0: https://ghcr.io
type: kubernetes.io/basic-auth
stringData:
  username: makocchan0509
  password: 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
