apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-repos-run-
spec:
  serviceAccountName: tekton-admin
  params:
  - name: bookinfo-url
    value: https://github.com/makocchan0509/bookinfo.git
  - name: bookinfo-revision
    value: main
  - name: bookinfo-manifests-url
    value: https://github.com/makocchan0509/bookinfo-manifests.git
  - name: bookinfo-manifests-revision
    value: main
  workspaces:
  - name: bookinfo
    persistentVolumeClaim:
      claimName: bookinfo
  - name: bookinfo-manifests
    persistentVolumeClaim:
      claimName: bookinfo-manifests
  pipelineRef:
    name: git-clone-repos
